using System;
using System.Linq;
using System.Runtime.Serialization;

namespace ProductCustomerApp
{
    public static class Northwind
    {
        // Categories and products data
        public static List<Category> Categories = new List<Category>
        {
            new Category
            {
                CategoryName = "Beverages",
                Products = new List<Product>
                {
                    new Product { ProductName = "Chai", UnitPrice = 18.00m },
                    new Product { ProductName = "Chang", UnitPrice = 19.00m }
                }
            },
            new Category
            {
                CategoryName = "Condiments",
                Products = new List<Product>
                {
                    new Product { ProductName = "Aniseed Syrup", UnitPrice = 10.00m },
                    new Product { ProductName = "Chef Anton's Cajun Seasoning", UnitPrice = 22.00m }
                }
            }
        };

        public static List<ICustomer> Customers = new List<ICustomer>()
        {
            new Customer { CompanyName = "Around the Horn",         City = "London" },
            new Customer { CompanyName = "B's Beverages",           City = "London" },
            new Customer { CompanyName = "Consolidated Holdings",   City = "London" },
            new Customer { CompanyName = "Eastern Connection",      City = "London" },
            new Customer { CompanyName = "North/South",             City = "London" },
            new Customer { CompanyName = "Seven Seas Imports",      City = "London" },
            new Customer { CompanyName = "The Big Cheese",          City = "Portland" },
            new Customer { CompanyName = "The Cracker Box",         City = "Portland" },
            new Customer { CompanyName = "The Food Depot",          City = "Portland" },
            new Customer { CompanyName = "The Great Outdoors",      City = "Portland" },
            new Customer { CompanyName = "The Pasta Place",         City = "Portland" },
            new Customer { CompanyName = "The Spices of Life",      City = "Portland" },
            new Customer { CompanyName = "Company A",               City = "Aachen" },
            new Customer { CompanyName = "Company B",               City = "Aachen" },
            new Customer { CompanyName = "Company C",               City = "Albuquerque" },
            new Customer { CompanyName = "Company D",               City = "Albuquerque" },
            new Customer { CompanyName = "Company E",               City = "Anchorage" },
            new Customer { CompanyName = "Company F",               City = "Anchorage" },
            new Customer { CompanyName = "Company G",               City = "Århus" },
            new Customer { CompanyName = "Company H",               City = "Århus" },
            new Customer { CompanyName = "Company I",               City = "Barcelona" },
            new Customer { CompanyName = "Company J",               City = "Barcelona" },
            new Customer { CompanyName = "Company K",               City = "Barquisimeto" },
            new Customer { CompanyName = "Company L",               City = "Barquisimeto" },
            new Customer { CompanyName = "Company M",               City = "Bergamo" },
            new Customer { CompanyName = "Company N",               City = "Bergamo" },
            new Customer { CompanyName = "Company O",               City = "Berlin" },
            new Customer { CompanyName = "Company P",               City = "Berlin" },
            new Customer { CompanyName = "Company Q",               City = "Bern" },
            new Customer { CompanyName = "Company R",               City = "Bern" },
            new Customer { CompanyName = "Company S",               City = "Boise" },
            new Customer { CompanyName = "Company T",               City = "Boise" },
            new Customer { CompanyName = "Company U",               City = "Bräcke" },
            new Customer { CompanyName = "Company V",               City = "Bräcke" },
            new Customer { CompanyName = "Company W",               City = "Brandenburg" },
            new Customer { CompanyName = "Company X",               City = "Brandenburg" },
            new Customer { CompanyName = "Company Y",               City = "Bruxelles" },
            new Customer { CompanyName = "Company Z",               City = "Bruxelles" },
            new Customer { CompanyName = "Company AA",              City = "Buenos Aires" },
            new Customer { CompanyName = "Company AB",              City = "Buenos Aires" },
            new Customer { CompanyName = "Company AC",              City = "Butte" },
            new Customer { CompanyName = "Company AD",              City = "Butte" },
            new Customer { CompanyName = "Company AE",              City = "Campinas" },
            new Customer { CompanyName = "Company AF",              City = "Campinas" },
            new Customer { CompanyName = "Company AG",              City = "Caracas" },
            new Customer { CompanyName = "Company AH",              City = "Caracas" },
            new Customer { CompanyName = "Company AI",              City = "Charleroi" },
            new Customer { CompanyName = "Company AJ",              City = "Charleroi" },
            new Customer { CompanyName = "Company AK",              City = "Cork" },
            new Customer { CompanyName = "Company AL",              City = "Cork" },
            new Customer { CompanyName = "Company AM",              City = "Cowes" },
            new Customer { CompanyName = "Company AN",              City = "Cowes" },
            new Customer { CompanyName = "Company AO",              City = "Cunewalde" },
            new Customer { CompanyName = "Company AP",              City = "Cunewalde" },
            new Customer { CompanyName = "Company AQ",              City = "Elgin" },
            new Customer { CompanyName = "Company AR",              City = "Elgin" },
            new Customer { CompanyName = "Company AS",              City = "Eugene" },
            new Customer { CompanyName = "Company AT",              City = "Eugene" },
            new Customer { CompanyName = "Company AU",              City = "Frankfurt a.M." },
            new Customer { CompanyName = "Company AV",              City = "Frankfurt a.M." },
            new Customer { CompanyName = "Company AW",              City = "Genève" },
            new Customer { CompanyName = "Company AX",              City = "Genève" },
            new Customer { CompanyName = "Company AY",              City = "Graz" },
            new Customer { CompanyName = "Company AZ",              City = "Graz" },
            new Customer { CompanyName = "Company BA",              City = "Helsinki" },
            new Customer { CompanyName = "Company BB",              City = "Helsinki" },
            new Customer { CompanyName = "Company BC",              City = "I. de Margarita" },
            new Customer { CompanyName = "Company BD",              City = "I. de Margarita" },
            new Customer { CompanyName = "Company BE",              City = "Kirkland" },
            new Customer { CompanyName = "Company BF",              City = "Kirkland" },
            new Customer { CompanyName = "Company BG",              City = "Kobenhavn" },
            new Customer { CompanyName = "Company BH",              City = "Kobenhavn" },
            new Customer { CompanyName = "Company BI",              City = "Köln" },
            new Customer { CompanyName = "Company BJ",              City = "Köln" },
            new Customer { CompanyName = "Company BK",              City = "Lander" },
            new Customer { CompanyName = "Company BL",              City = "Lander" },
            new Customer { CompanyName = "Company BM",              City = "Leipzig" },
            new Customer { CompanyName = "Company BN",              City = "Leipzig" },
            new Customer { CompanyName = "Company BO",              City = "Lille" },
            new Customer { CompanyName = "Company BP",              City = "Lille" },
            new Customer { CompanyName = "Company BQ",              City = "Lisboa" },
            new Customer { CompanyName = "Company BR",              City = "Lisboa" },
            new Customer { CompanyName = "Company BU",              City = "Luleå" },
            new Customer { CompanyName = "Company BV",              City = "Luleå" },
            new Customer { CompanyName = "Company BW",              City = "Lyon" },
            new Customer { CompanyName = "Company BX",              City = "Lyon" },
            new Customer { CompanyName = "Company BY",              City = "Madrid" },
            new Customer { CompanyName = "Company BZ",              City = "Madrid" },
            new Customer { CompanyName = "Company CA",              City = "Mannheim" },
            new Customer { CompanyName = "Company CB",              City = "Mannheim" },
            new Customer { CompanyName = "Company CC",              City = "Marseille" },
            new Customer { CompanyName = "Company CD",              City = "Marseille" },
            new Customer { CompanyName = "Company CE",              City = "México D.F." },
            new Customer { CompanyName = "Company CF",              City = "México D.F." },
            new Customer { CompanyName = "Company CG",              City = "Montréal" },
            new Customer { CompanyName = "Company CH",              City = "Montréal" },
            new Customer { CompanyName = "Company CI",              City = "München" },
            new Customer { CompanyName = "Company CJ",              City = "München" },
            new Customer { CompanyName = "Company CK",              City = "Münster" },
            new Customer { CompanyName = "Company CL",              City = "Münster" },
            new Customer { CompanyName = "Company CM",              City = "Nantes" },
            new Customer { CompanyName = "Company CN",              City = "Nantes" },
            new Customer { CompanyName = "Company CO",              City = "Oulu" },
            new Customer { CompanyName = "Company CP",              City = "Oulu" },
            new Customer { CompanyName = "Company CQ",              City = "Paris" },
            new Customer { CompanyName = "Company CR",              City = "Paris" },
            new Customer { CompanyName = "Company CS",              City = "Regio E" },
            new Customer { CompanyName = "Company CT",              City = "Regio E" },
            new Customer { CompanyName = "Company CU",              City = "Reims" },
            new Customer { CompanyName = "Company CV",              City = "Reims" },
            new Customer { CompanyName = "Company CW",              City = "Resende" },
            new Customer { CompanyName = "Company CX",              City = "Resende" },
            new Customer { CompanyName = "Company CY",              City = "Rio de Janeiro" },
            new Customer { CompanyName = "Company CZ",              City = "Rio de Janeiro" },
            new Customer { CompanyName = "Company DA",              City = "Salzburg" },
            new Customer { CompanyName = "Company DB",              City = "Salzburg" },
            new Customer { CompanyName = "Company DC",              City = "San Cristóbal" },
            new Customer { CompanyName = "Company DD",              City = "San Cristóbal" },
            new Customer { CompanyName = "Company DE",              City = "São Paulo" },
            new Customer { CompanyName = "Company DF",              City = "São Paulo" },
            new Customer { CompanyName = "Company DG",              City = "Seattle" },
            new Customer { CompanyName = "Company DH",              City = "Seattle" },
            new Customer { CompanyName = "Company DI",              City = "Sevilla" },
            new Customer { CompanyName = "Company DJ",              City = "Sevilla" },
            new Customer { CompanyName = "Company DK",              City = "Stavern" },
            new Customer { CompanyName = "Company DL",              City = "Stavern" },
            new Customer { CompanyName = "Company DM",              City = "Stowe" },
            new Customer { CompanyName = "Company DN",              City = "Stowe" },
            new Customer { CompanyName = "Company DO",              City = "Strasbourg" },
            new Customer { CompanyName = "Company DP",              City = "Strasbourg" },
            new Customer { CompanyName = "Company DQ",              City = "Stuttgart" },
            new Customer { CompanyName = "Company DR",              City = "Stuttgart" },
            new Customer { CompanyName = "Company DS",              City = "Torino" },
            new Customer { CompanyName = "Company DT",              City = "Torino" },
            new Customer { CompanyName = "Company DU",              City = "Toulouse" },
            new Customer { CompanyName = "Company DV",              City = "Toulouse" },
            new Customer { CompanyName = "Company DW",              City = "Tsawassen" },
            new Customer { CompanyName = "Company DX",              City = "Tsawassen" },
            new Customer { CompanyName = "Company DY",              City = "Vancouver" },
            new Customer { CompanyName = "Company DZ",              City = "Vancouver" },
            new Customer { CompanyName = "Company EA",              City = "Versailles" },
            new Customer { CompanyName = "Company EB",              City = "Versailles" },
            new Customer { CompanyName = "Company EC",              City = "Walla Walla" },
            new Customer { CompanyName = "Company ED",              City = "Walla Walla" },
            new Customer { CompanyName = "Company EE",              City = "Warszawa" },
            new Customer { CompanyName = "Company EF",              City = "Warszawa" }
        };
    }

    
}
